### ISSUE TITLE
Username for authentication is using "From" email address instead of Username from settings

### ISSUE THREAD

**Issue by sergiomiranda-outsystems** [PaulHoOutsystems/email_extended#2]
Hello,

First, thank you for creating this and making it available in the OutSystems Forge and the source code here.

I am using this to do some tests and it seems that the Username configured in the App settings is not being used for authentication, but instead it's using the "From" email address.

https://github.com/PaulHoOutsystems/email_extended/blob/a18b167062c1dce1ba6b7a2755dfccdbdad0f5ea/src/EmailExtended_Ext.cs#L208

This will work for some cases, but not others where the username for authentication is not the same as the address in the "From:" field.

**Comment by PaulHoOutsystems** [comment]
Thanks for highlighting this! This is fixed and is available in build number 20241122223309. The updated Forge component has been submitted for approval and should be available in 2 to 3 working days. 

Thank you for using this ODC Forge component.
