### ISSUE TITLE
Unexpect behavior at sendEmail

### ISSUE THREAD

**Issue by johnesthomas** [PaulHoOutsystems/email_extended#3]
Using the sendEmail action, it is only possible to sendEmail if the input parameters to, cc, bcc and replyTo are filled in. I believe that only the "to" input parameter is necessary, right?

Sending only "to" parameter, I have this following exception.

![image](https://github.com/user-attachments/assets/5685fce7-0538-4eca-b29f-bf9ad09892c5)
![image](https://github.com/user-attachments/assets/b6b2f37f-6d90-417b-896b-9c7aed4042e8)

**Comment by PaulHoOutsystems** [comment]
Hi @johnesthomas even though cc, bcc, replyTo are "optional", they should be pass in as an empty list if there is nothing for those values.

**Comment by johnesthomas** [comment]
Very strange then, the email is only sent successfully when all these fields are filled in.

**Comment by PaulHoOutsystems** [comment]
Just to enure that my understanding is correct. You are passing as empty list for "cc", "bcc" and "replyTo"?

**Comment by johnesthomas** [comment]
Exactly, when I fill in these items, the email is sent successfully, if I don't enter any value, the email is not sent.

**Comment by PaulHoOutsystems** [comment]
Is the replyTo list an empty list that you are passing over?

**Comment by johnesthomas** [comment]
Yes, since all these parameters require a text list, I'm just passing an empty text element home.

**Comment by PaulHoOutsystems** [comment]
This is indeed strange because, the unit test sendEmail_Ext_test1 is scenario that matches your case and it is showing up as pass. For sendEmail_Ext_test1, cc, bcc and replyTo are all empty list. See line 105 to 119 of the unit test case and you will notice that.

**Comment by johnesthomas** [comment]
Hi Paul, before I was passing an empty element within each list, that's why the error was happening. But now, I had to create a local variable of the text list type and pass it through the lists that are mandatory. I believe that the ideal would be to just remove the mandatory nature of these fields. Thanks for the support!
